version: "3.5"

services:
  checkout:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=checkout
      - ENVIRONMENT=production
      - CHECKOUT_URL=${CHECKOUT_URL}
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=grafana-agent
    command: "-checkout"
    ports:
      - ${CHECKOUT_PORT}:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
    labels:
      - "grafana_logs=true"
      - "grafana_metrics=true"
      - "service=checkout"
  payment:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=payment
      - ENVIRONMENT=production
      - CHECKOUT_URL=${CHECKOUT_URL}
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=grafana-agent
    command: "-payment"
    ports:
      - ${PAYMENT_PORT}:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
    labels:
      - "grafana_logs=true"
      - "grafana_metrics=true"
      - "service=payment"
  order:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=order
      - ENVIRONMENT=production
      - CHECKOUT_URL=${CHECKOUT_URL}
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=grafana-agent
    command: "-order"
    ports:
      - ${ORDER_PORT}:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
    labels:
      - "grafana_logs=true"
      - "grafana_metrics=true"
      - "service=order"
  warehouse:
    build: .
    environment:
      - PORT=8080
      - SERVICE_NAME=warehouse
      - ENVIRONMENT=production
      - CHECKOUT_URL=${CHECKOUT_URL}
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=grafana-agent
    command: "-warehouse"
    ports:
      - ${WAREHOUSE_PORT}:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
    labels:
      - "grafana_logs=true"
      - "grafana_metrics=true"
      - "service=warehouse"
  chaos:
    build: .
    environment:
      - CHECKOUT_URL=${CHECKOUT_URL}
      - PAYMENT_URL=${PAYMENT_URL}
      - ORDER_URL=${ORDER_URL}
      - WAREHOUSE_URL=${WAREHOUSE_URL}
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=grafana-agent
    command: "-chaos"
    restart: unless-stopped
  grafana-agent:
    env_file: ./grafana-agent/.env
    image: grafana/agent:v0.30.2
    volumes:
      - ./.docker/grafana-agent/tmp/data:/etc/agent/data
      - ./grafana-agent/grafana-agent.yml:/etc/agent/agent.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -config.expand-env
